name: "CI"
on: push

permissions:
  packages: write
  contents: read

jobs:
  create_image:
    name: "Create image"

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: oscarock/microservice:1.0.0
          context: .
          cache-from: type=registry,ref=oscarock/microservice
          cache-to: type=inline
